#!/usr/bin/env bash
set -x

GOVERSION=1.23.3
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"
GOPATH="${HOME}/go"
GOBIN="${GOPATH/:*}/bin"

_installGo() {
    curl -OL https://golang.org/dl/go${GOVERSION}.${OS}-${ARCH}.tar.gz
    sudo tar -C /usr/local -xf go${GOVERSION}.${OS}-${ARCH}.tar.gz
    sudo mkdir -p /usr/local/go/pkg/mod
    rm go${GOVERSION}.${OS}-${ARCH}.tar.gz
    PATH="${PATH}:${GOBIN}"
}


if [[ -d ${GOBIN} ]]; then
    INSTALLED_GO_VERSION="$(${GOBIN}/go version | { read _ _ v _; echo ${v#go}; })" || false
    if [[ ${INSTALLED_GO_VERSION:-} != ${GOVERSION} ]]; then
        rm -rf /usr/local/go
        _installGo
    fi
else
    _installGo
fi
